include:
    - database/db-compose.yaml
    - jaeger/jaeger-compose.yaml
    - nginx/nginx-compose.yaml
    - kafka/kafka-compose.yaml

services:
    app:
        container_name: app
        profiles: [backend, full]
        build:
            context: backend
            dockerfile: Dockerfile
            target: final
        env_file:
            - ./backend/.env.docker
        expose:
            - "8080"
        depends_on:
            db:
                condition: service_healthy
            jaeger:
                condition: service_started
            app_init:
                condition: service_completed_successfully

    app_init:
        container_name: app_init
        profiles: [backend, full]
        build:
            context: backend
            dockerfile: Dockerfile
            target: migrate
        volumes:
            - ./backend/migrations:/migrations
        env_file:
            - ./backend/.env.docker
        depends_on:
            - db

    frontend:
        container_name: frontend
        profiles: [frontend, full]
        build:
            context: frontend
            dockerfile: Dockerfile
        expose:
            - "3000"
        depends_on:
            - app
            - dozzle

    dozzle:
        container_name: dozzle
        profiles: [logging, full]
        environment:
            - DOZZLE_BASE=/logs
        image: amir20/dozzle:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        expose:
            - "8080"

    email:
        container_name: email
        profiles: [backend, full]
        build:
            context: email
            dockerfile: Dockerfile
        env_file:
            - ./email/.env.docker
        expose:
            - "8081"
        depends_on:
            - kafka0